name: Build GTNH Mod

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/reusable-workflow.yml@master
    secrets: inherit